analyzer:
  errors:
    deprecated_member_use: ignore
    unreachable_switch_default: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:flutter_lints/flutter.yaml
