// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq-88r6Iyv-PNOJuZyzRxdq1J6NLs6Scw',
    appId: '1:453576031191:web:209efe2fe729476d9f2992',
    messagingSenderId: '453576031191',
    projectId: 'bazarlive-fee1a',
    authDomain: 'bazarlive-fee1a.firebaseapp.com',
    storageBucket: 'bazarlive-fee1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXSe0_YPOgK_rWvXvAExnteM7o2bMfU60',
    appId: '1:453576031191:android:4e1dfd493c5d2dd39f2992',
    messagingSenderId: '453576031191',
    projectId: 'bazarlive-fee1a',
    storageBucket: 'bazarlive-fee1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0dYlrQetOcuBzIYU-vMGe-iNwbGYAR-Y',
    appId: '1:453576031191:ios:82c05ec79ca9c12e9f2992',
    messagingSenderId: '453576031191',
    projectId: 'bazarlive-fee1a',
    storageBucket: 'bazarlive-fee1a.firebasestorage.app',
    androidClientId: '453576031191-hpb1o2n862pq19utvfgsa4nm9a859lnf.apps.googleusercontent.com',
    iosClientId: '453576031191-foejdgbrg8a8ki6fioa1fqaek268v9b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.localmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0dYlrQetOcuBzIYU-vMGe-iNwbGYAR-Y',
    appId: '1:453576031191:ios:82c05ec79ca9c12e9f2992',
    messagingSenderId: '453576031191',
    projectId: 'bazarlive-fee1a',
    storageBucket: 'bazarlive-fee1a.firebasestorage.app',
    androidClientId: '453576031191-hpb1o2n862pq19utvfgsa4nm9a859lnf.apps.googleusercontent.com',
    iosClientId: '453576031191-foejdgbrg8a8ki6fioa1fqaek268v9b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.localmarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq-88r6Iyv-PNOJuZyzRxdq1J6NLs6Scw',
    appId: '1:453576031191:web:6a31daebb0a5649b9f2992',
    messagingSenderId: '453576031191',
    projectId: 'bazarlive-fee1a',
    authDomain: 'bazarlive-fee1a.firebaseapp.com',
    storageBucket: 'bazarlive-fee1a.firebasestorage.app',
  );
}
